version: '2'
services:
  web:
    build: .
    ports:
      - 3000:3000
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    env_file:
      - .env.sample
  vue:
    build: ./client
    ports:
      - 8080:8080
    #command: webpack -w --config ./config/webpack.config.js
    command: webpack-dev-server --config ./webpack.config.js --host=0.0.0.0 --inline --hot
    volumes:
      - .:/app
      - /app/client/node_modules
